name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 2221
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/projects/bot-microsoft-teams

            # 🔥 Load NVM (WAJIB)
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            # 🔥 Pakai Node 24
            nvm use 24

            # Debug (optional tapi recommended)
            node -v
            npm -v
            which node

            git fetch origin main
            git reset --hard origin/main

            npm install --omit=dev

            # Pastikan pm2 ada
            command -v pm2 || npm install -g pm2

            pm2 reload ecosystem.config.js
            pm2 save